jwt:
  secret: mysupercomplexsecret
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
spring:
  #  profiles:
  #    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/zimdrive?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    password:
    username: root
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
      servlet:
        multipart:
          enabled: true
          file-size-threshold: 2KB
          max-file-size: 200MB
          max-request-size: 215MB
  sql:
    init:
      mode: never
      continue-on-error: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: javaspringboot7@gmail.com
    password: gpceghqgktqlvfye
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
swagger:
  api:
    title: SecureCapital
    description: API for Secure Capital
    version: 0.9
    termsOfServiceUrl: google.com
    contact:
      name: Your Contact Name Here
      url: Your Contact URL Here

frontend:
  url: https://processmanagement.tanawellnesscoaching.com
  resetUrl: /user/verify/password